services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: theovalguide
      POSTGRES_USER: theoval
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: